### ISSUE TITLE
loading old planning scenes with updated robot geometry shows collisions

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#31] opened 2012-11-15 23:25 UTC
Not sure how much related this is with the issue of how planning scenes are stored in the database, but the following will not work:

1) Create a planning scene for a robot
2) Update the robot description (e.g add a gripper), and regenerate the moveit package
3) Load the planning scene of the first step

All the new links appear always in collision. However, it works with new scenes.

**Comment by isucan** [comment] 2012-11-27 16:58
Mario, the planning scene also includes the collision matrix to use. Since the robot name was left to be the same, the complete scene is loaded, including the collision matrix. But that old collision matrix does not include the new data, so you get collisions, which is in fact, the expected behaviour. If you use a different name for the robot, all is well. 
Another way to do this would be to have an option to explicitly load just the scene geometry. If we decide to pursue this feature, we should open a ticket about that (closing this one).

**Closed as completed by isucan** 2012-11-27 16:58 UTC
