### ISSUE TITLE
Mesh switching bug in Rviz

### ISSUE THREAD

**Issue by clintP** [moveit/moveit_ros#398] opened 2014-01-13 19:25 UTC
I'm having a problem with having 2 meshes in Rviz. I'm using two .stl files as meshes in the scene right now, but apparently it works for any kind of mesh ( see: https://groups.google.com/d/topic/moveit-users/cNm0EIMpo5Q/discussion)

What happens is that when you move the meshes around sometimes they switch, or one mesh transforms into the other mesh for a split second.

Here's a video of what I'm talking about: http://youtu.be/gzEq382jRMk

It starts happening about 14 seconds in

**Comment by acornacorn** [comment] 2014-01-13 20:36
Can you describe how you are inserting the meshes?  E.g. is this a rviz Display plugin that you wrote, or are you using an interactive marker server running in a node separate from rviz, or what?  Seeing the actual sourcecode you are running would help too.

**Comment by mikeferguson** [comment] 2014-01-13 22:20
This is a duplicate of https://github.com/ros-planning/moveit_ros/issues/348.

In addition, I've seen this even when not using the interactive markers to move the meshes around, but if they are simply updating due to the planning scene being updated. It appears to only affect non-attached meshes, and affects both the planning scene plugin and the moveit planning plugin.

I've spent quite a bit of time trying to track this down, but I never did find a fix. I did go in and print out memory locations and mesh sizes in visualization/rviz_plugin_render_tools/src/render_shapes.cpp and didn't see anything funky in my case. It is my opinion that something might be going strange in lower level rviz/ogre stuff due to us adding objects via https://github.com/ros-planning/moveit_ros/blob/hydro-devel/visualization/rviz_plugin_render_tools/src/render_shapes.cpp#L196 and removing them by deleting the boost shared ptrs (one quick test I did was to comment out https://github.com/ros-planning/moveit_ros/blob/hydro-devel/visualization/rviz_plugin_render_tools/src/render_shapes.cpp#L71 at which point I got lots and lots of repeated instances of my object as I moved it around, but at no point did my 2 meshes change into each other). I don't know enough about rviz/ogre to really dig much deeper -- perhaps @hersh might have some ideas?

**Comment by clintP** [comment] 2014-01-15 21:57
Sorry if any of this sounds really ignorant, I just got started with ROS and rviz fairly recently.

I'm not using any code as far as I can tell... all I did was open my launch file so my robot (yaskawa motoman sia5d) could be displayed in Rviz and spawned two .STL files from Scene Objects -> Import File in the Rviz window, then dragged them around in Rviz using the interactive markers

"Seeing the actual sourcecode you are running would help too." -> I don't know what this means, but here's my launch file to open my robot in Rviz:

http://pastebin.com/UAyCa35j

Thanks in advance for taking to time to look at this btw

**Comment by hersh** [comment] 2014-02-19 02:18
This bug is actually in rviz code.  I fixed it in a pull request there: https://github.com/ros-visualization/rviz/pull/724

**Comment by mikeferguson** [comment] 2014-12-01 05:40
This was fixed some time ago in rviz.

**Closed as completed by mikeferguson** 2014-12-01 05:40 UTC
