### ISSUE TITLE
Make benchmark service more general

### ISSUE THREAD

**Issue by marioprats** [moveit/moveit_ros#191] opened 2013-02-05 00:46 UTC
Would it make sense to generalize the benchmark backend so that we can benchmark moveit-based functionality other than planners? The input to the benchmark service is a MotionPlanRequest, which is needed for planners, but we may need to benchmark reachability, trajectories (#190), interpolatedIK and other stuff that is part of moveit but lay outside planners.

I would propose to set the current implementation (removing the --goal-existence-only) as a special case for planners, and then add other benchmarks for goals, interpolatedIK, etc. We can create an abstract class to define the common interface. Does this sound reasonable?

**Comment by isucan** [comment] 2013-02-05 21:33
Yes, we need to do this, but we need to do things in a principled manner so that there is some communality in the code written. We should set up a meeting to discuss.
Add other interested parties?
Attn: @mateiciocarlie @sachinchitta @KaijenHsiao @adamantivm @acornacorn

**Comment by mateiciocarlie** [comment] 2013-02-06 01:53
Yes, we do need this functionality. I think Mario captured our current and future use cases very well. I could participate in the meeting, but I don't know if I would have much to add - between @marioprats and @isucan all the needed expertise is there :)

Is this a duplicate of #186?

**Comment by marioprats** [comment] 2013-02-06 02:57
Well, #186 is the special case for benchmarking trajectories. This one has more to do with refactoring the benchmark backend to better solve #186 and the others to come. @isucan let's have a talk tomorrow if you have time.

**Comment by isucan** [comment] 2013-02-06 03:25
Sounds good to me

**Comment by sachinchitta** [comment] 2013-02-06 06:34
The benchmark service (as it exists) essentially wraps the current motion plan request. Some of the functionality here could still exist there: e.g. following cartesian trajectories. Other benchmarking services should use the corresponding msgs that already exist in moveit: e.g. all kinematics reachability messages should be based off the current IK calls (or something derived from them). Interpolated IK could happen through the trajectory constraints (with two waypoints). 

As far as possible, we should reuse existing ROS messages, etc. and not add new ones.

**Comment by isucan** [comment] 2013-04-15 19:22
we made some progress in this direction, closing for now. we should open a new ticket when we come back to this.

**Closed as completed by isucan** 2013-04-15 19:22 UTC
