### ISSUE TITLE
Remove need for Rviz to launch with kinematics.yaml parameters

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_ros#198] opened 2013-02-12 00:36 UTC
It seems counter-intuitive and unnecessary that the Motion Planning Plugin requires that Rviz first be launched with ROBOT_moveit_config/config/kinematics.yaml loaded into Rviz's namespace. If you fail to do this, the interactive markers will not work properly and no warning or error will appear explaining why. To reiterate, currently a launch file that starts rviz and uses the motion planning plugin looks like this:

```
  <node name="$(anon rviz)" launch-prefix="$(arg launch_prefix)" pkg="rviz" type="rviz" 
    respawn="false" output="screen" args="-d $(find clam_moveit_config)/launch/moveit.rviz" >
    <rosparam command="load" file="$(find clam_moveit_config)/config/kinematics.yaml"/>
  </node>
```

Why not just have that information for the plugin be pulled in from the move_group node that must be launched along side rviz (that is required, right?).

**Comment by isucan** [comment] 2013-02-12 00:39
i agree. this is a duplicate of #180

**Closed as completed by isucan** 2013-02-12 00:39 UTC
Labels: enhancement, nice to have
