### ISSUE TITLE
Print Summary of Reachability results

### ISSUE THREAD

**Issue by chadrockey** [moveit/moveit_ros#10] opened 2012-10-03 01:09 UTC
It would be helpful if one of the final ROS_INFO calls were some sort of summary or statistics about the reachability exercise just performed.

For instance, something as simple as: "Successfully reached 670 of 1000 poses".  This should help as a simple quantitative metric that's easy to output.

Other averages or standard deviations may also be useful, such as "Average maneuverability index/deviation", but I do not specifically have a use case for other metrics at this time.

**Comment by mateiciocarlie** [comment] 2012-12-13 17:04
Closing this as a duplicate of #69. If additional result forms are needed, please add them there.

**Closed as completed by mateiciocarlie** 2012-12-13 17:04 UTC
